demo:
	gfortran -g lsq.f90 lsq_demo.f90

demo2:
	gfortran lsq.f90 test1.f90

test615:
	gfortran lsq.f90 toms615.f90 test615.f90 -o test615

subset:
	gfortran lsq.f90 find_sub.f90 subset.f90 -o subset
